######################################################################
# Automatically generated by qmake (3.1) Sat Aug 2 14:28:32 2025
######################################################################

TEMPLATE = app
TARGET = SSRT-Telemetry
INCLUDEPATH += .

# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Input
HEADERS += imudata.hpp \
           labelmanager.hpp \
           LocationInfo.hpp \
           maplabel.hpp \
           roverangle.hpp \
           rovergpsd.h \
           rovermqtt.hpp \
           roverTracker.hpp \
           sciencesensors.hpp \
           install/qtmqtt/src/mqtt/qmqttauthenticationproperties.h \
           install/qtmqtt/src/mqtt/qmqttclient.h \
           install/qtmqtt/src/mqtt/qmqttclient_p.h \
           install/qtmqtt/src/mqtt/qmqttconnection_p.h \
           install/qtmqtt/src/mqtt/qmqttconnectionproperties.h \
           install/qtmqtt/src/mqtt/qmqttconnectionproperties_p.h \
           install/qtmqtt/src/mqtt/qmqttcontrolpacket_p.h \
           install/qtmqtt/src/mqtt/qmqttglobal.h \
           install/qtmqtt/src/mqtt/qmqttmessage.h \
           install/qtmqtt/src/mqtt/qmqttmessage_p.h \
           install/qtmqtt/src/mqtt/qmqttpublishproperties.h \
           install/qtmqtt/src/mqtt/qmqttpublishproperties_p.h \
           install/qtmqtt/src/mqtt/qmqttsubscription.h \
           install/qtmqtt/src/mqtt/qmqttsubscription_p.h \
           install/qtmqtt/src/mqtt/qmqttsubscriptionproperties.h \
           install/qtmqtt/src/mqtt/qmqtttopicfilter.h \
           install/qtmqtt/src/mqtt/qmqtttopicname.h \
           install/qtmqtt/src/mqtt/qmqtttype.h \
           install/qtmqtt/tests/common/broker_connection.h \
           install/qtmqtt/build/include/QtMqtt/qmqttauthenticationproperties.h \
           install/qtmqtt/build/include/QtMqtt/qmqttclient.h \
           install/qtmqtt/build/include/QtMqtt/qmqttconnectionproperties.h \
           install/qtmqtt/build/include/QtMqtt/qmqttglobal.h \
           install/qtmqtt/build/include/QtMqtt/qmqttmessage.h \
           install/qtmqtt/build/include/QtMqtt/qmqttpublishproperties.h \
           install/qtmqtt/build/include/QtMqtt/qmqttsubscription.h \
           install/qtmqtt/build/include/QtMqtt/qmqttsubscriptionproperties.h \
           install/qtmqtt/build/include/QtMqtt/qmqtttopicfilter.h \
           install/qtmqtt/build/include/QtMqtt/qmqtttopicname.h \
           install/qtmqtt/build/include/QtMqtt/qmqtttype.h \
           install/qtmqtt/build/include/QtMqtt/qtmqttexports.h \
           install/qtmqtt/build/include/QtMqtt/qtmqttversion.h \
           install/qtmqtt/examples/mqtt/quickpublication/qmlmqttclient.h \
           install/qtmqtt/examples/mqtt/quicksubscription/qmlmqttclient.h \
           install/qtmqtt/examples/mqtt/simpleclient/mainwindow.h \
           install/qtmqtt/examples/mqtt/subscriptions/mainwindow.h \
           install/qtmqtt/examples/mqtt/subscriptions/subscriptionwindow.h \
           install/qtmqtt/examples/mqtt/websocketsubscription/clientsubscription.h \
           install/qtmqtt/examples/mqtt/websocketsubscription/websocketiodevice.h \
           install/qtmqtt/tests/manual/consolepubsub/configuration.h \
           install/qtmqtt/build/include/QtMqtt/6.8.3/QtMqtt/private/qmqttclient_p.h \
           install/qtmqtt/build/include/QtMqtt/6.8.3/QtMqtt/private/qmqttconnection_p.h \
           install/qtmqtt/build/include/QtMqtt/6.8.3/QtMqtt/private/qmqttconnectionproperties_p.h \
           install/qtmqtt/build/include/QtMqtt/6.8.3/QtMqtt/private/qmqttcontrolpacket_p.h \
           install/qtmqtt/build/include/QtMqtt/6.8.3/QtMqtt/private/qmqttmessage_p.h \
           install/qtmqtt/build/include/QtMqtt/6.8.3/QtMqtt/private/qmqttpublishproperties_p.h \
           install/qtmqtt/build/include/QtMqtt/6.8.3/QtMqtt/private/qmqttsubscription_p.h
FORMS += install/qtmqtt/examples/mqtt/simpleclient/mainwindow.ui \
         install/qtmqtt/examples/mqtt/subscriptions/mainwindow.ui \
         install/qtmqtt/examples/mqtt/subscriptions/subscriptionwindow.ui
SOURCES += imudata.cpp \
           labelmanager.cpp \
           main.cpp \
           maplabel.cpp \
           roverangle.cpp \
           rovergpsd.cpp \
           rovermqtt.cpp \
           roverTracker.cpp \
           sciencesensors.cpp \
           build/qrc_Resources.cpp \
           build/ssrttelemetry_qmltyperegistrations.cpp \
           build/Desktop_Qt_6_8_0-Debug/appssrtelemetry_qmltyperegistrations.cpp \
           build/Desktop_Qt_6_8_0-Debug/qrc_Resources.cpp \
           build/Desktop_Qt_6_8_0-Debug/ssrttelemetry_qmltyperegistrations.cpp \
           build/Desktop_Qt_6_8_0-Debug_OLD/appssrtelemetry_qmltyperegistrations.cpp \
           build/Desktop_Qt_6_8_0-Debug_OLD/qrc_Resources.cpp \
           build/Desktop_Qt_6_8_0-Debug_OLD/ssrttelemetry_qmltyperegistrations.cpp \
           build/SSRTTelemetry_autogen/mocs_compilation.cpp \
           build/Desktop_Qt_6_8_0-Debug/appSSRTelemetry_autogen/mocs_compilation.cpp \
           build/Desktop_Qt_6_8_0-Debug/SSRTTelemetry_autogen/mocs_compilation.cpp \
           build/Desktop_Qt_6_8_0-Debug_OLD/appSSRTelemetry_autogen/mocs_compilation.cpp \
           build/Desktop_Qt_6_8_0-Debug_OLD/SSRTTelemetry_autogen/mocs_compilation.cpp \
           build/CMakeFiles/3.30.5/CompilerIdCXX/CMakeCXXCompilerId.cpp \
           install/qtmqtt/src/mqtt/qmqttauthenticationproperties.cpp \
           install/qtmqtt/src/mqtt/qmqttclient.cpp \
           install/qtmqtt/src/mqtt/qmqttconnection.cpp \
           install/qtmqtt/src/mqtt/qmqttconnectionproperties.cpp \
           install/qtmqtt/src/mqtt/qmqttcontrolpacket.cpp \
           install/qtmqtt/src/mqtt/qmqttmessage.cpp \
           install/qtmqtt/src/mqtt/qmqttpublishproperties.cpp \
           install/qtmqtt/src/mqtt/qmqttsubscription.cpp \
           install/qtmqtt/src/mqtt/qmqttsubscriptionproperties.cpp \
           install/qtmqtt/src/mqtt/qmqtttopicfilter.cpp \
           install/qtmqtt/src/mqtt/qmqtttopicname.cpp \
           install/qtmqtt/src/mqtt/qmqtttype.cpp \
           build/Desktop_Qt_6_8_0-Debug/CMakeFiles/3.29.3/CompilerIdCXX/CMakeCXXCompilerId.cpp \
           build/Desktop_Qt_6_8_0-Debug_OLD/CMakeFiles/3.29.3/CompilerIdCXX/CMakeCXXCompilerId.cpp \
           install/qtmqtt/examples/mqtt/quickpublication/main.cpp \
           install/qtmqtt/examples/mqtt/quickpublication/qmlmqttclient.cpp \
           install/qtmqtt/examples/mqtt/quicksubscription/main.cpp \
           install/qtmqtt/examples/mqtt/quicksubscription/qmlmqttclient.cpp \
           install/qtmqtt/examples/mqtt/simpleclient/main.cpp \
           install/qtmqtt/examples/mqtt/simpleclient/mainwindow.cpp \
           install/qtmqtt/examples/mqtt/subscriptions/main.cpp \
           install/qtmqtt/examples/mqtt/subscriptions/mainwindow.cpp \
           install/qtmqtt/examples/mqtt/subscriptions/subscriptionwindow.cpp \
           install/qtmqtt/examples/mqtt/websocketsubscription/clientsubscription.cpp \
           install/qtmqtt/examples/mqtt/websocketsubscription/main.cpp \
           install/qtmqtt/examples/mqtt/websocketsubscription/websocketiodevice.cpp \
           install/qtmqtt/tests/auto/conformance/tst_conformance.cpp \
           install/qtmqtt/tests/auto/qmqttclient/tst_qmqttclient.cpp \
           install/qtmqtt/tests/auto/qmqttconnectionproperties/tst_qmqttconnectionproperties.cpp \
           install/qtmqtt/tests/auto/qmqttcontrolpacket/tst_qmqttcontrolpacket.cpp \
           install/qtmqtt/tests/auto/qmqttlastwillproperties/tst_qmqttlastwillproperties.cpp \
           install/qtmqtt/tests/auto/qmqttpublishproperties/tst_qmqttpublishproperties.cpp \
           install/qtmqtt/tests/auto/qmqttsubscription/tst_qmqttsubscription.cpp \
           install/qtmqtt/tests/auto/qmqttsubscriptionproperties/tst_qmqttsubscriptionproperties.cpp \
           install/qtmqtt/tests/auto/qmqtttopicfilter/tst_qmqtttopicfilter.cpp \
           install/qtmqtt/tests/auto/qmqtttopicname/tst_qmqtttopicname.cpp \
           install/qtmqtt/tests/benchmarks/qmqttclient/tst_qmqttclient.cpp \
           install/qtmqtt/tests/manual/consolepubsub/main_pub.cpp \
           install/qtmqtt/tests/manual/consolepubsub/main_sub.cpp \
           install/qtmqtt/tests/manual/sslconfiguration/main.cpp \
           install/qtmqtt/build/CMakeFiles/3.22.1/CompilerIdC/CMakeCCompilerId.c \
           install/qtmqtt/build/CMakeFiles/3.22.1/CompilerIdCXX/CMakeCXXCompilerId.cpp \
           install/qtmqtt/build/src/mqtt/Mqtt_autogen/mocs_compilation.cpp \
           install/qtmqtt/tests/libfuzzer/mqtt/data_receive/main.cpp
RESOURCES += application.qrc \
             Resources.qrc \
             build/SSRTelemetry/appSSRTTelemetry_qml_module_dir_map.qrc \
             build/SSRTelemetry/SSRTTelemetry_qml_module_dir_map.qrc \
             build/Desktop_Qt_6_8_0-Debug/SSRTelemetry/appSSRTelemetry_qml_module_dir_map.qrc \
             build/Desktop_Qt_6_8_0-Debug/SSRTelemetry/SSRTTelemetry_qml_module_dir_map.qrc \
             build/Desktop_Qt_6_8_0-Debug_OLD/SSRTelemetry/appSSRTelemetry_qml_module_dir_map.qrc \
             build/Desktop_Qt_6_8_0-Debug_OLD/SSRTelemetry/SSRTTelemetry_qml_module_dir_map.qrc
TRANSLATIONS += install/qtmqtt/build/CMakeFiles/benchmark.dir/compiler_depend.ts \
                install/qtmqtt/build/CMakeFiles/bootstrap_tools.dir/compiler_depend.ts \
                install/qtmqtt/build/CMakeFiles/doc_tools.dir/compiler_depend.ts \
                install/qtmqtt/build/CMakeFiles/docs.dir/compiler_depend.ts \
                install/qtmqtt/build/CMakeFiles/docs_qtmqtt.dir/compiler_depend.ts \
                install/qtmqtt/build/CMakeFiles/generate_docs.dir/compiler_depend.ts \
                install/qtmqtt/build/CMakeFiles/generate_docs_qtmqtt.dir/compiler_depend.ts \
                install/qtmqtt/build/CMakeFiles/host_tools.dir/compiler_depend.ts \
                install/qtmqtt/build/CMakeFiles/html_docs.dir/compiler_depend.ts \
                install/qtmqtt/build/CMakeFiles/html_docs_qtmqtt.dir/compiler_depend.ts \
                install/qtmqtt/build/CMakeFiles/install_docs.dir/compiler_depend.ts \
                install/qtmqtt/build/CMakeFiles/install_docs_qtmqtt.dir/compiler_depend.ts \
                install/qtmqtt/build/CMakeFiles/install_html_docs.dir/compiler_depend.ts \
                install/qtmqtt/build/CMakeFiles/install_html_docs_qtmqtt.dir/compiler_depend.ts \
                install/qtmqtt/build/CMakeFiles/install_qch_docs.dir/compiler_depend.ts \
                install/qtmqtt/build/CMakeFiles/install_qch_docs_qtmqtt.dir/compiler_depend.ts \
                install/qtmqtt/build/CMakeFiles/prepare_docs.dir/compiler_depend.ts \
                install/qtmqtt/build/CMakeFiles/prepare_docs_qtmqtt.dir/compiler_depend.ts \
                install/qtmqtt/build/CMakeFiles/qch_docs.dir/compiler_depend.ts \
                install/qtmqtt/build/CMakeFiles/qch_docs_qtmqtt.dir/compiler_depend.ts \
                install/qtmqtt/build/CMakeFiles/qpa_default_plugins.dir/compiler_depend.ts \
                install/qtmqtt/build/CMakeFiles/qpa_plugins.dir/compiler_depend.ts \
                install/qtmqtt/build/CMakeFiles/qt_plugins.dir/compiler_depend.ts \
                install/qtmqtt/build/CMakeFiles/qt_plugins_qtmqtt.dir/compiler_depend.ts \
                install/qtmqtt/build/CMakeFiles/qt_plugins_qtmqtt_recursive.dir/compiler_depend.ts \
                install/qtmqtt/build/CMakeFiles/qtmqtt.dir/compiler_depend.ts \
                install/qtmqtt/build/CMakeFiles/qtmqtt_changelogs.dir/compiler_depend.ts \
                install/qtmqtt/build/CMakeFiles/qtmqtt_cmake_files.dir/compiler_depend.ts \
                install/qtmqtt/build/CMakeFiles/qtmqtt_coin_files.dir/compiler_depend.ts \
                install/qtmqtt/build/CMakeFiles/qtmqtt_extra_files.dir/compiler_depend.ts \
                install/qtmqtt/build/CMakeFiles/qtmqtt_licenses.dir/compiler_depend.ts \
                install/qtmqtt/build/CMakeFiles/qtmqtt_src.dir/compiler_depend.ts \
                install/qtmqtt/build/CMakeFiles/qtmqtt_src_for_examples.dir/compiler_depend.ts \
                install/qtmqtt/build/CMakeFiles/sbom.dir/compiler_depend.ts \
                install/qtmqtt/build/CMakeFiles/sbom_qtmqtt.dir/compiler_depend.ts \
                install/qtmqtt/build/CMakeFiles/sync_headers.dir/compiler_depend.ts \
                install/qtmqtt/build/CMakeFiles/thirdparty_sync_headers.dir/compiler_depend.ts \
                install/qtmqtt/build/config.tests/binary_for_strip_built/CMakeFiles/lib1.dir/compiler_depend.ts \
                install/qtmqtt/build/config.tests/binary_for_strip_built/CMakeFiles/print_lib_path.dir/compiler_depend.ts \
                install/qtmqtt/build/src/mqtt/CMakeFiles/docs_Mqtt.dir/compiler_depend.ts \
                install/qtmqtt/build/src/mqtt/CMakeFiles/generate_docs_Mqtt.dir/compiler_depend.ts \
                install/qtmqtt/build/src/mqtt/CMakeFiles/generate_repo_docs_Mqtt.dir/compiler_depend.ts \
                install/qtmqtt/build/src/mqtt/CMakeFiles/generate_top_level_docs_Mqtt.dir/compiler_depend.ts \
                install/qtmqtt/build/src/mqtt/CMakeFiles/html_docs_Mqtt.dir/compiler_depend.ts \
                install/qtmqtt/build/src/mqtt/CMakeFiles/install_docs_Mqtt.dir/compiler_depend.ts \
                install/qtmqtt/build/src/mqtt/CMakeFiles/install_html_docs_Mqtt.dir/compiler_depend.ts \
                install/qtmqtt/build/src/mqtt/CMakeFiles/install_qch_docs_Mqtt.dir/compiler_depend.ts \
                install/qtmqtt/build/src/mqtt/CMakeFiles/Mqtt.dir/compiler_depend.ts \
                install/qtmqtt/build/src/mqtt/CMakeFiles/Mqtt_autogen.dir/compiler_depend.ts \
                install/qtmqtt/build/src/mqtt/CMakeFiles/Mqtt_automoc_json_extraction.dir/compiler_depend.ts \
                install/qtmqtt/build/src/mqtt/CMakeFiles/Mqtt_lib_pri.dir/compiler_depend.ts \
                install/qtmqtt/build/src/mqtt/CMakeFiles/Mqtt_sync_all_public_headers.dir/compiler_depend.ts \
                install/qtmqtt/build/src/mqtt/CMakeFiles/Mqtt_sync_headers.dir/compiler_depend.ts \
                install/qtmqtt/build/src/mqtt/CMakeFiles/Mqtt_version_script.dir/compiler_depend.ts \
                install/qtmqtt/build/src/mqtt/CMakeFiles/prepare_docs_Mqtt.dir/compiler_depend.ts \
                install/qtmqtt/build/src/mqtt/CMakeFiles/qattributionsscanner_Mqtt.dir/compiler_depend.ts \
                install/qtmqtt/build/src/mqtt/CMakeFiles/qch_docs_Mqtt.dir/compiler_depend.ts \
                install/qtmqtt/build/src/mqtt/CMakeFiles/qch_repo_docs_Mqtt.dir/compiler_depend.ts \
                install/qtmqtt/build/src/mqtt/CMakeFiles/qch_top_level_docs_Mqtt.dir/compiler_depend.ts \
                install/qtmqtt/build/src/mqtt/CMakeFiles/sync_all_public_headers.dir/compiler_depend.ts
